FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y \
&& apt install php7.4-fpm php7.4-mysql php7.4-xml nginx fcgiwrap composer mariadb-server vim openssh-server openssh-client -y \
&& mkdir -p /var/www/fusionsuite \
&& git clone https://github.com/fusionSuite/backend.git  /var/www/fusionsuite/backend \
&& rm /etc/nginx/sites-enabled/default

RUN service mariadb start
# Allow SSH Root Login
RUN sed -i 's|^#PermitRootLogin.*|PermitRootLogin yes|g' /etc/ssh/sshd_config
RUN echo "root:root123" | chpasswd

COPY ./backend/fusionsuite.conf /etc/nginx/sites-enabled/fusionsuite.conf
COPY ./backend/phinx.php /var/www/fusionsuite/backend

WORKDIR /var/www/fusionsuite/backend
COPY ./backend/configure-mariadb.sql .
COPY ./backend/run.sh .
RUN chmod +x ./run.sh
RUN composer install
CMD [ "/bin/bash", "./run.sh" ]